### ISSUE TITLE
Çoklu Attribute ve Çoklu StokItem Uyumsuzluğu

### ISSUE THREAD

**Issue by mertdogan** [ahmetozalp/N11-PHP-Soap-Api#1]
Eğer ürün kaydederken attribute olarak 1'den fazla alan girilmesi gerekiyorsa (ki zorunlu alan olarak 1'den fazlaysa bundan kaçış yok) ayrıca ürünün 1'den fazla stoğu varsa (stokitem olarak) bu kod çalışmamaktadır.

Güncellenmesi çok faydalı olacaktır.

**Comment by ahmetozalp** [comment]
bildirim için teşeşkurler update i yakın zamanda yaparım
