### ISSUE TITLE
Bir Hata Veriyor: Uncaught Error: Class 'SoapClient' not found.

### ISSUE THREAD

**Issue by agahtoruk** [ahmetozalp/N11-PHP-Soap-Api#3]
Class'ı kullanmaya çalıştığımda aşağıdaki hatayı veriyor. Yardımcı olur musunuz?

Fatal error: Uncaught Error: Class 'SoapClient' not found in C:\xampp\htdocs\Soap\n11.class.php:13
Stack trace: #0 C:\xampp\htdocs\Soap\n11.class.php(17): N11->setUrl('https://api.n11...') #1 C:\xampp\htdocs\Soap\index.php(10): N11->GetTopLevelCategories() #2 {main} thrown in C:\xampp\htdocs\Soap\n11.class.php on line 13

**Comment by fayihyalcin** [comment]
Bu hatayı çözdünüz mü?

**Comment by agahtoruk** [comment]
> Bu hatayı çözdünüz mü?

Ben maalesef çözemedim. Bu hata size de mi çıktı?

**Comment by fayihyalcin** [comment]
Evet maalesef çıktı. Nasıl çözülür hiçbir fikrim yok

**Comment by mandza** [comment]
PHP SoapClient eklentisini yüklemiş miydiniz?
PHP varsayılan kurulumunda bu gelmiyor.
